### ISSUE TITLE
Allow modifying the Entries

### ISSUE THREAD

**Issue by Mannshoch** [sefeng211/faviconSwitcher#12]
Allow modifying the Entries.
I have a huge set of URL inserted. Now I have to modify their URL. Please resize the Overview Window and add a Pencil icon which allow to modify the URL-

**Comment by sefeng211** [comment]
Yeah, this makes sense. I'll try to find some time this week to make something work. 

I am happy to take patches too if you are interested :)

**Comment by Mannshoch** [comment]
I'm not a Developer, sorry. It's my hobby to support Software I like and use with IMHO good idea.

**Comment by sefeng211** [comment]
I think the latest update with version 0.4.0 fixes. 

(Sorry, I know it's a long time....)
