### ISSUE TITLE
Favicons fail to load after updating to Firefox 130.0

### ISSUE THREAD

**Issue by nrhinehart** [sefeng211/faviconSwitcher#15]
The favicons I've configured no longer apply after restarting Firefox today, instead, they are now their original favicons.

It appears Firefox has updated itself to 130.0 earlier today https://www.mozilla.org/en-US/firefox/130.0/releasenotes/

Inspecting the browser console, it appears that some security setting is preventing the image from being loaded from the extension.
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/afaa14b1-a1c1-44f4-bdf6-6141b2894f99">

I also downloaded and installed Firefox 129.0.2, and confirmed that the extension does not have the same problem on version (129.0.2) for me -- instead, my favicon is loaded correctly. I also do not see a similar error in the browser console of Firefox 129.0.2.

**Comment by sefeng211** [comment]
Thanks! https://bugzilla.mozilla.org/show_bug.cgi?id=1795082 is the cause here. I'll fix it and push an update
