### ISSUE TITLE
Req: XPI-file: Non-cryptic name

### ISSUE THREAD

**Issue by Jonta** [sefeng211/faviconSwitcher#8]
Right now, going to `~/.mozilla/firefox/[profile-ID]/extensions/`, this extension is identified by an opaque hex-string

An example of an extension that has a clear name, is HTTPS Everywhere: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

=)

**Comment by sefeng211** [comment]
Thanks, having a clear name is better!

**Comment by sefeng211** [comment]
So I assed this, it turned out that we can't do it, because it'd be a new extension if I uploaded it to AMO...
